Repository agrotis-io/vraw, pull requests merged in 2018-02, with the labels that each got.

#2 update Clock component
  src/components/Clock/Clock.test.tsx
  src/components/Clock/Clock.tsx
Labels: enhancement

#12 ci(travis-ci): update release script to run only on merged pull requests
  .travis.yml
Labels: CI

#14 docs(readme): update readme with vraw logomark, fixed badges urls
  .gitignore
  README.md
  images/intro.jpg
  images/travisci-options.png
  package.json
  yarn.lock
Labels: docs, fix

#18 Danger commit messages validation
  dangerfile.js
Labels: CI, enhancement
